// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttwjflzfghlpsoyncecg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0d2pmbHpmZ2hscHNveW5jZWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4MDM0MTUsImV4cCI6MjA5ODM3OTQxNX0.CEFm8aDKE-OSWqayy8MeAj4l91QCdzGIoSkRpfDJCwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});